### PR TITLE
Use katcp-codec 0.1.0

### PR DESCRIPTION
**Pull request by bmerry**
Replaces the beta version that was being used.

### CODE REVIEW

**Review by ludwigschwardt — APPROVED** [review]

**Review by james-smith-za — APPROVED** [review]
Random macos build failing though.

**Comment by bmerry** [comment]
> Random macos build failing though.

It's Coveralls. I still need to look into why the service is returning an error for the MacOS coverage.

**Comment by ludwigschwardt** [comment]
You could always just run coveralls on `ubuntu-20.04` by adding that to the `include` part of the `matrix` setting.

**Comment by bmerry** [comment]
> You could always just run coveralls on `ubuntu-20.04` by adding that to the `include` part of the `matrix` setting. Do we really need it on macOS (I guess so if there are OS-dependent code paths)?

I think the reason for running coverage on MacOS was to get coverage for the fallback code that replaces timex.

**Comment by bmerry** [comment]
The coveralls failure seems to be an intermittent thing (maybe a race condition?) so I'm going to ignore it for now.

**Pull request merged**
